version: "3.9"
services:
  postgres:
    image: postgres:13.3
    env_file:
      - ./.env
    environment:
      POSTGRES_DB: ${SQL_DATABASE}
      POSTGRES_USER: ${SQL_USER}
      POSTGRES_PASSWORD: ${SQL_PASSWORD}
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - .:/var/lib/postgresql/data
      - ./sqls:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
