name: CI
on:
  push:
    branches:
      - feature/*
jobs:
  api-e2e-tests:
    runs-on: ubuntu-latest
    container: node:16
    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres:13.3
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm ci --legacy-peer-deps

      - name: Prisma db migrare
        run: npx nx db-push prisma
        env:
          DATABASE_URL: postgresql://postgres:postgres@postgres:5432/test?schema=public

      - name: Prisma seed
        run: npx nx seed prisma

      - name: Run e2e api test
        run: npx nx run server:test-e2e
